nelmio_api_doc:
    documentation:
        info:
            title: Doc API Sireturn
            description: Les endpoints de l'API Sireturn
            version: 1.0.0
        tags:
            - name: User
            - name: Company
    areas: # to filter documented areas
        path_patterns:
            - ^/auth
            - ^/api
